services:
  pgdb:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - ./storage/pg:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpassword
